### ISSUE TITLE
Issues with df and emmeans

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/orchaRd#1]
Noting an unanticipated problem. When models are fit without test = "t" then the model$ddf slot contains NA. This causes unanticipated issues with marginal means function as upper.CI and lower.CI cannot be computed, but are rather changed to l.asymp.CI and u.asymp.CI and predictions intervals are not calculated. This is an issue with how metafor models are working

**Comment by daniel1noble** [comment]
E.g.
eklof_MR<-metafor::rma.mv(yi=yi, V=vi, mods=~ Grazer.type, random=list(~1|ExptID,
+ ~1|Datapoint), data=eklof)
results <- orchaRd::marginal_means(eklof_MR, mod = "1", group = "ExptID", data=eklof) # FAILS

But,

eklof_MR<-metafor::rma.mv(yi=yi, V=vi, mods=~ Grazer.type, random=list(~1|ExptID,
+ ~1|Datapoint), method = "t", data=eklof)
results <- orchaRd::marginal_means(eklof_MR, mod = "1", group = "ExptID", data=eklof) 
results
     name   estimate   lowerCL    upperCL   lowerPR  upperPR
1 Intrcpt -0.6355998 -1.125271 -0.1459286 -2.899852 1.628652  # CORRECT

**Comment by daniel1noble** [comment]
Need a check in the marginal means to sort this out

**Comment by itchyshin** [comment]
@daniel1noble - I have had this issue before - I think I know how I resolved this earlier
