### ISSUE TITLE
Reordering moderators in Orchard Plots

### ISSUE THREAD

**Issue by anantapantulasa** [daniel1noble/orchaRd#11]
I am trying to change the order of how the moderators are presented in the orchard plot. For example, in the following image, I want to move Chordata up, then Mollusca, etc. How can I move the moderators in the order that I want in an orchard plot?
![image](https://user-images.githubusercontent.com/42307681/197370165-dda77387-0f7c-4ab1-aa3c-ed46e56ddae1.png)

**Comment by daniel1noble** [comment]
HI @anantapantulasa. There is currently no argument, but this should be fairly easy to do by just setting levels of a factor. Here's an example:


data(lim)
str(lim)
lim$vi<-(1/sqrt(lim$N - 3))^2
lim$Phylum <- with(lim, factor(Phylum, levels = sample(unique(lim$Phylum), replace = FALSE)))
lim_MR<-metafor::rma.mv(yi=yi, V=vi, mods=~Phylum-1, random=list(~1|Article, ~1|Datapoint), data=lim)
summary(lim_MR)

#Plot the meta-regression model
orchaRd::orchard_plot(lim_MR, mod = "Phylum", group = "Article", data = lim, xlab = "Correlation coefficient", 
                      alpha = 0.5, transfm = "tanh", angle = 45, N = "N", cb = FALSE)

**Comment by daniel1noble** [comment]
I'll note that I just randomly ordered the Phylum (just because I was lazy ;) 

You can feed in a vector with the specific order you want to `levels` and that should do it.

**Comment by anantapantulasa** [comment]
Thanks! And, can you center the sample size information, i.e. the "k= #(grouping variable)" information to the effect size line?
