### ISSUE TITLE
Error in data.frame(yi, vi, moderator, stdy, type) :    arguments imply differing number of rows: 79, 1, 93

### ISSUE THREAD

**Issue by Chengyu10103** [daniel1noble/orchaRd#13]
Hello, I had one problem when I used orchaRd, please see below:
![image](https://user-images.githubusercontent.com/117347717/199679439-9bda8c8f-608d-4703-8e2b-cfdf5b248af6.png)

I am looking forward to your answer. Thank you!

**Comment by daniel1noble** [comment]
Hi. Do you have the latest version installed? The group argument is not needed for rma.mv. I would exclude missing data before fitting the model. See if that fixes the issue.
