### ISSUE TITLE
How to move k away from the dashed vertical line 

### ISSUE THREAD

**Issue by Arisede** [daniel1noble/orchaRd#14]
Hello everyone,
I have two issues with the orchard plot function. First, I am getting an error message "Error: Discrete value supplied to continuous scale" if I add xlim() to orchard_plot(). However, I then set ylim() instead then the code worked, but the code used to work smoothly with xlim() before. See the pictures below. Now I do not understand how to specify axis limits with orchard_plot(). Can anyone help me understand? Second, how do I move k away from the dashed vertical line?
![Screenshot (78)](https://user-images.githubusercontent.com/118527926/202822649-fb32c48c-b0cd-4119-a9a1-de5088e3f8e0.png)
![Screenshot (79)](https://user-images.githubusercontent.com/118527926/202822678-d63c9bd6-197e-4db4-baea-8e9bfed37f61.png)
ashed vertical line?

**Comment by daniel1noble** [comment]
Hi,

In regards to your first point, orchard used coord_flip(). So, the x and y are flipped around. This could explain your first point and why slim works. 

Second, you'll need to change xlim/ylim to move k/g off the line. But, a simple solution is to just suppress k and g from the plot and add it on yourself manually. You can do this by setting the arguments `k = FALSE` and `g = FALSE`. 

Hope that helps.
Dan

**Comment by Arisede** [comment]
Hi Daniel,
Thank you for the prompt response. Much appreciated. Yes! This has helped me.

Many thanks.
Arisede
