### ISSUE TITLE
Documentation proof-reading

### ISSUE THREAD

**Issue by roseodea** [daniel1noble/orchaRd#15]
Keeping track of progress on the branch [documentation_edits](https://github.com/daniel1noble/orchaRd/tree/documentation_edits)
- [x] bubble_plot.R
- [x] caterpillars.R
- [x] data.R
- [x] i2_ml.R
- [x] mod_results.R
- [x] orchard_plot.R
- [x] r2_ml.R
- [x] submerge.R

**Comment by daniel1noble** [comment]
Thanks @roseodea !
