### ISSUE TITLE
Additional options for 'k.pos' in orchard_plot()

### ISSUE THREAD

**Issue by befriendabacterium** [daniel1noble/orchaRd#29]
**Is your feature request related to a problem? Please describe.**
For the 'k.pos' argument in orchard_plot(), there are only three options (right, left and none - could do with making this clearer in the help file under Arguments too) and these aren't always sufficient to produce legible k.pos labels (see picture).  

**Describe the solution you'd like**
Maybe some more options like 'farright' or 'farleft' (though maybe not that precise wording lol), and/or an option to specify the exact coordinates of the labels (at least on the x-axis).

**Describe alternatives you've considered**
Could label manually but would be good to have it integrated into the plotting function.

**Additional context**
See demonstrative image - argument here is set to 'right'. 
![image](https://github.com/daniel1noble/orchaRd/assets/42059798/1a68cbfc-f2b3-4528-973a-1349a75db007)

Thanks once again, really great package for better meta-analysis plots!

**Comment by befriendabacterium** [comment]
Attempted to implement this myself by forking your repo and raising a pull request for you to inspect. See what you think!
https://github.com/daniel1noble/orchaRd/pull/30

**Comment by daniel1noble** [comment]
Great! Thanks Matt. Sorry. I just seen this. Looks like you already fixed. Thanks! I've merged in as it should be good and passes tests

**Comment by befriendabacterium** [comment]
Cool thanks! No worries I was just acutely aware that I was loading you with feature requests so thought I'd try solve this one myself. Glad it made the grade! Might need some more documentation/error messages for incorrect entry when specifying the position by text (right, leftnon
