### ISSUE TITLE
The logarithmic response ratio (effect size) is converted to the percentage change and plotted

### ISSUE THREAD

**Issue by ling9802** [daniel1noble/orchaRd#37]
The percentage change is probably somewhat more indicative of the effect of the treatment I'm concerned about, what should I do to plot it instead of plotting effect size.

**Comment by daniel1noble** [comment]
This is not currently possible for log response ratios. Sorry. I'll add it as a feature to add down the road

**Comment by ling9802** [comment]
Thank you for your reply and look forward to your better work.

**Comment by daniel1noble** [comment]
This has now been added using the `transf` argument. It still needs testing but you should be able to convert lnRR to percentage
