### ISSUE TITLE
Features to make caterpillar plot more equivalent to orchaRd plot

### ISSUE THREAD

**Issue by befriendabacterium** [daniel1noble/orchaRd#42]
**Is your feature request related to a problem? Please describe.**
I really like that orchaRd also has a caterpillars() function to plot this alternative way of displaying the same information, but going further with this by adding some options to colour the caterpillar plot by study and change the orientation (so effect size is on y axis) would a nice feature to facilitate closer comparison.

**Describe the solution you'd like**
1. Option to colour by study as in orchard_plot()
2. Option to flip orientation of plot as in orchard_plot()

**Describe alternatives you've considered**
Could manually recolour and reorientate the orchard plot object I suppose but can be tricky esp. with re-colouring as the syntax required is a bit different.

**Comment by befriendabacterium** [comment]
Here's my proposed colouring-by-study feature addition https://github.com/daniel1noble/orchaRd/pull/43

**Comment by befriendabacterium** [comment]
And when/if you've merged that, here's my proposed flipping orientation solution.

https://github.com/daniel1noble/orchaRd/pull/44

**Comment by daniel1noble** [comment]
Merged now
