### ISSUE TITLE
`bubble_plot` error

### ISSUE THREAD

**Issue by itchyshin** [daniel1noble/orchaRd#47]
@daniel1noble - I am putting it here - I will see what is happening.

It was working till I updated all R and RStudio. One other member reported the same error. 

I will show the error when we meet

**bubble_plot error**
```
> bubble_plot(mod_ord,
+              mod = "Treat_No",
+              group = "RecNo",
+              xlab = "The number of simuli",
+              g = TRUE)
Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
  replacement has 0 rows, data has 640
```

**Desktop (please complete the following information):**
 - OS: Ventura 13.5

**Comment by itchyshin** [comment]
I have been working on solving an error with the bubble_plot function for the past two weeks, but I have not been able to solve it. So, I am reaching out to all of you for advice.
When I try to run the bubble_plot function, the following error is displayed:

```
> bubble_plot(model1,
            mod = "Area_pattern",
            group = "Study_ID",
            xlab = "Area (mm2)")
Error in `$<-.data.frame`(`*tmp*`, "condition", value = integer(0)) : 
 replacement has 0 rows, data has 263
```

If you got and solved this error before, I would greatly appreciate it if you could share the solution. Also, if I have made mistakes, please let me know.
orchard_plot function runs without any issues.

I tried this with R 4.2.3 and 4.3.1, using the latest version of R Studio, metafor, and orchaRd packages, but the error occurred.
Additionally, I tried on two different Macs (M1 and Intel Mac), but the error occurred on both PCs.

You can review the example model code and more details by clicking the following link:
[R/Error_example.R](https://github.com/Ayumi-495/eyespot/blob/d9f8ad9064cd2dcb904e8907e4310bd9265f24cf/R/Error_example.R)

**Comment by daniel1noble** [comment]
@itchyshin Thanks. I'll see if I can poke around at this next week, early week. Sorry. At the moment I am completely swamped with teaching - marking, practicals etc. Can you send me your example.R script in slack. Doesn't seem to link here. Maybe a private repo is why

**Comment by itchyshin** [comment]
@daniel1noble - it was my fault. Last time, I added a reordering of the factors to match data and labels, but I added it the wrong place. Now fixed. Can you please update the package (an interesting thing is that Lorenzo told me your example worked but bubble did not work for me and 2 other people). I will show you what was the issue on Monday. Thanks!

**Comment by daniel1noble** [comment]
Thanks for fixing it @itchyshin! You’re quick. I pulled down and had a look. I see what was happening. I did all the checks and everything should be good to go! 

Thanks again
Dan

**Comment by itchyshin** [comment]
Thanks @daniel1noble  - catch up with you on Monday
