### ISSUE TITLE
creating cv_ml and m1_ml

### ISSUE THREAD

**Issue by itchyshin** [daniel1noble/orchaRd#48]
@itchyshin to create

- [x] cv_ml - mulitlevel version of CV (heterogeneity)
- [x] m1_ml - mulitlevel version of M1 (heterogeneity)

extra stuff
- [ ] check i2_ml - it fails when the sample size is small - investigate how small

**Comment by itchyshin** [comment]
@daniel1noble - great to catch up. I pushed the first draft of M1 and CV functions - please check. Also, i2_ml no longer has the `data` argument.

I will check it out when boot fails a bit later

**Comment by daniel1noble** [comment]
@itchyshin Thanks! I've checked i2, updated the tests to deal with drop in data argument and updated the documentation for new functions. 

Great to catch up today!

**Comment by itchyshin** [comment]
I think this is done and dusted
