### ISSUE TITLE
Error in model.frame.default(formula, data = data, ...) :    'data' must be a data.frame, environment, or list

### ISSUE THREAD

**Issue by kiran-lee** [daniel1noble/orchaRd#5]
Hello,

When using orchard_plot or model_results, I run into the following error message:
Error in model.frame.default(formula, data = data, ...) : 
  'data' must be a data.frame, environment, or list

Yet I am definitely specifying the dataframe used for the model.

Do you have any suggestions for the cause?

Kiran

PhD student
Division of Biosciences
Sheffield University

**Comment by anantapantulasa** [comment]
I'm having the same issue. Is there a way to fix this?

**Comment by daniel1noble** [comment]
Hi, I believe this was an issue with `emmeans`, which I think we've now sorted out. I've pushed updates to orchard to deal with it, so a fresh install might work @kiran-lee and @anantapantulasa . Sorry I missed all this!

**Comment by daniel1noble** [comment]
An addition to this, the vignette is updated and found [here](https://daniel1noble.github.io/orchaRd/). Just in case you're using something slightly older. The way some arguments work has changed for reasons related to how other packages have also changed, so, this might solve your problems too

**Comment by daniel1noble** [comment]
I'll close this issue assuming that the updates have solve this problem, but if not we can re-open
