### ISSUE TITLE
Error in orchaRD::mod_results 

### ISSUE THREAD

**Issue by mad30bekch** [daniel1noble/orchaRd#54]
Hi, 
I want to create a forest plot using OrchaRd plot, but It keeps giving me an error when using any of these functions: orchaRD::mod_results or orchaRd::orchard_plot.  I am using the orchaRd package Version 2.0

Can you please help solve it? Thank you 

Total_NPK_PUB =  metafor::rma.mv(lnrr, v, 
                                 random = ~ 1 | publication_title / unique_id, test = "t",
                                 method = "REML", data=Soil_total_NPK)

f <- orchaRd::mod_results(Total_NPK_PUB, mod = "1", group = "unique_id", data = Soil_total_NPK)  # Replace 'Soil_total_NPK' with your actual dataset

orchaRd::orchard_plot(output5, mod = "metrics4", group = "publication_title", xlab = "log(Response ratio) (lnRR)",
                      transfm = "none", 
                      data = Total_NPK_PUB)

Error in (function(ordinal, ordinal.dim = NULL) { : 
  unused argument (at = NULL)

**Comment by daniel1noble** [comment]
Hi. You need to input 'f' object, not 'output5' to orchaRd plot.

**Comment by mad30bekch** [comment]
Sorry, I pasted the wrong code. Here is the code I used 

Total_NPK_PUB = metafor::rma.mv(lnrr, v,
random = ~ 1 | publication_title / unique_id, test = "t",
method = "REML", data=Soil_total_NPK)

f <- orchaRd::mod_results(Total_NPK_PUB, mod = "1", group = "unique_id", data = Soil_total_NPK) 

Here is the error the code returned:

Error in (function(ordinal, ordinal.dim = NULL) { :
unused argument (at = NULL)

**Comment by daniel1noble** [comment]
'data' is no longer a necessary argument. See here: https://daniel1noble.github.io/orchaRd/. Can you remove this and see if that error disappears?

**Comment by mad30bekch** [comment]
Yes, I removed it, but then I got the error below. If I add the data then it gives the error I posted earlier

Total_NPK_PUB =  metafor::rma.mv(lnrr, v, 
                                 random = ~ 1 | publication_title / unique_id, test = "t",
                                 method = "REML", data=Soil_total_NPK)

f <- orchaRd::mod_results(Total_NPK_PUB, mod = "1", group = "unique_id")

Error in orchaRd::mod_results(Total_NPK_PUB, mod = "1", group = "unique_id") : 
  Please specify the 'data' argument by providing the data used to fit the model. See ?mod_results

**Comment by daniel1noble** [comment]
This would mean you’re using an older version of orchard. I’d  suggest a fresh install of the orchaRd package. DanOn 26 Oct 2023, at 1:16 am, mad30bekch ***@***.***> wrote:﻿
Yes, I removed it, but then I got the error below. If I add the data then it gives the error I posted earlier
Total_NPK_PUB =  metafor::rma.mv(lnrr, v,
random = ~ 1 | publication_title / unique_id, test = "t",
method = "REML", data=Soil_total_NPK)
f <- orchaRd::mod_results(Total_NPK_PUB, mod = "1", group = "unique_id")
Error in orchaRd::mod_results(Total_NPK_PUB, mod = "1", group = "unique_id") :
Please specify the 'data' argument by providing the data used to fit the model. See ?mod_results
