### ISSUE TITLE
you can add %

### ISSUE THREAD

**Issue by itchyshin** [daniel1noble/orchaRd#55]
@daniel1noble 

I finally figured out how to add %

```
...
label= paste0("italic(I)^{2} == ", rev(i2_tot), "*\"%\""), 
parse = TRUE)
```
![Screenshot 2023-12-22 at 12 21 00 pm](https://github.com/daniel1noble/orchaRd/assets/12078523/87256603-9192-488b-9732-e8b22c25f244)

**Comment by daniel1noble** [comment]
This is great! Thanks Shinichi. I've added and updated vignette
