### ISSUE TITLE
Can't use orchaRd::mod_results function

### ISSUE THREAD

**Issue by chliuhq** [daniel1noble/orchaRd#56]
**Describe the bug**
Can't use orchaRd::mod_results function
Error in `[.data.frame`(as.data.frame.data.frame(x), ...) : 

**To Reproduce**
data(english)

english <- escalc(measure = "SMD", n1i = NStartControl, sd1i = SD_C, m1i = MeanC,
    n2i = NStartExpt, sd2i = SD_E, m2i = MeanE, var.names = c("SMD", "vSMD"), data = english)

english_MA <- rma.mv(yi = SMD, V = vSMD, random = list(~1 | StudyNo, ~1 | EffectID),
    data = english)
summary(english_MA)

model_results <- orchaRd::mod_results(english_MA, mod = "1", at = NULL,  group = "StudyNo")
model_results

I got "Error in `[.data.frame`(as.data.frame.data.frame(x), ...) : "

**Screenshots**
![image](https://github.com/daniel1noble/orchaRd/assets/38576927/c640fa19-19ae-4e63-80b1-950142c7e641)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Rstudio
 - Version R-4.3.1

**Comment by daniel1noble** [comment]
Hi. What version of orchaRd are you using. These tests work fine on my computer and pass all tests.

**Comment by daniel1noble** [comment]
Not heard anything else about this so assuming it's fixed. Will close for now
