### ISSUE TITLE
Twig.size changes mean point size, not prediction interval

### ISSUE THREAD

**Issue by CReemts** [daniel1noble/orchaRd#59]
I am using orchard_plot to create graphs from a meta-analysis. I tried to change the weight of the prediction interval using twig.size as described in the function help section. However, any number that I entered for twig.size ended up affecting the mean point. Trunk.size and branch.size both work as expected.

**Comment by itchyshin** [comment]
Thanks @CReemts for flagging this. I am away at the moment but I will check this out as soon as I have time

**Comment by daniel1noble** [comment]
@CReemts Thanks for catching this. The problem appears to be a reversal of the size and flatten arguments in geom_pointrange. This was an easy fix by flipping them around. Should hopefully work now

**Comment by daniel1noble** [comment]
Update. Sorry. It wasn't the reversal, but rather we needed to use a different argument from flatten because flatten controls both line and point. Although, the arguments were still reversed.
