### ISSUE TITLE
Error in model.frame.default(formula, data = data, ...) :    'data' must be a data.frame, environment, or list

### ISSUE THREAD

**Issue by anantapantulasa** [daniel1noble/orchaRd#6]
Hi, 
I ran the following code (note: data was loaded, and effect sizes were calculated before running this line):

_______________________________________________________________________________________________________________________________________
overall_all_MA <- rma.mv(yi = lnRR, V = vlnRR, random = list(~1 | experimental_id, ~1 | study),
                     data = data_es)
summary(overall_all_MA)
orchaRd::orchard_plot(overall_all_MA, mod = "1", data = data_es, group = "experimental_id", xlab = "log Response Ratio",
                      transfm = "none")
_______________________________________________________________________________________________________________________________________

and received the following error from only the last line - running the orchard_plot() function:
_______________________________________________________________________________________________________________________________________
Error in model.frame.default(formula, data = data, ...) : 
  'data' must be a data.frame, environment, or list
_______________________________________________________________________________________________________________________________________
To check if data_es was a data frame, I used the class() function:
_______________________________________________________________________________________________________________________________________
> class(data_es)
[1] "escalc"     "data.frame"
_______________________________________________________________________________________________________________________________________

So, data_es is a data_frame, but I am getting an error that data_es is not a data frame. 
Data_es contains my originally collected data and the effect size calculations. 

I used the code from "[Example 1](https://daniel1noble.github.io/orchaRd/#Example_1:_Dietary_Restriction_and_Lifespan)" in the orchaRd vignette. I want to get an orchard plot for all my data - not just the moderator analysis. Another observation: when I ran the code from "[Example 2](https://daniel1noble.github.io/orchaRd/#Example_2:_Predation_and_Invertebrate_Community)" in the orchaRd vignette, I was able to produce sub-group analysis plots. However, I need the intercept plot (i.e. the plot for the whole dataset, without any moderators) similar to the picture below. Could you please help to resolve this issue or provide another approach to plot the data?

![image](https://user-images.githubusercontent.com/42307681/183150818-659ed6e1-da14-4443-9fb6-fe875d26db48.png)

**Comment by daniel1noble** [comment]
@anantapantulasa Hi again. We've been busy updating various things over the last few weeks in preparation for a broader release. There was an issue with `emmeans` as they recently did an update and it resulted in it causing a bunch of downstream functions to fail. These issues should now be sorted, so I suggest a fresh install of orchaRd and it should work. Although, we'd need to sort your install issue out first. All the tests on my end, and the vignette examples (different from tests) are all running fine so far.

**Comment by daniel1noble** [comment]
I'll close this issue assuming that the updates have solve this problem, but if not we can re-open

**Comment by anantapantulasa** [comment]
Hi Dan,
Sorry for not replying. I was able to get the graph! I tried after re-downloading `emmeans` and `RTools`, and I was able to get the graph! 
Is it possible to thicken the black outline around the circle, which is the overall estimate data point, as shown in the red circle in Fig 2?
![image](https://user-images.githubusercontent.com/42307681/183927453-ef2b43ea-fdd9-415c-8a98-e2387779326f.png)
![image](https://user-images.githubusercontent.com/42307681/183927964-a34ea015-0594-4c49-af86-865769a458eb.png)

**Comment by daniel1noble** [comment]
@anantapantulasa Yes. You should be able to do that fairly easily. if you look at the help file for `orchard_plot` you will see a few arguments: 
trunk.size = 3,
  branch.size = 1.2,
  twig.size = 0.5

That will allow you to change the size of those geom objects
