### ISSUE TITLE
2 new issues in the latest version

### ISSUE THREAD

**Issue by itchyshin** [daniel1noble/orchaRd#60]
@daniel1noble - I am reporting 2 issues I came across today using the latest version 

1. now the default trunk.size seems to be too big - see examples (bring it down to 1 from 3?)

![Screenshot 2024-04-05 at 7 42 47 AM](https://github.com/daniel1noble/orchaRd/assets/12078523/03a48049-0dfa-4149-b684-90748ce8b5b7)
![Screenshot 2024-04-05 at 7 42 52 AM](https://github.com/daniel1noble/orchaRd/assets/12078523/a8f5a927-e8a4-43a2-9dd1-969323576e5e)

trunck.size = 1

![Screenshot 2024-04-05 at 7 49 12 AM](https://github.com/daniel1noble/orchaRd/assets/12078523/e5b7021a-7069-4919-88af-30458ec5436d)

2. now the previous issue of not being able to deal with missing data came back (I will try to investigate)

![Screenshot 2024-04-05 at 7 45 27 AM](https://github.com/daniel1noble/orchaRd/assets/12078523/de83ccce-003a-44eb-9f9a-4e6c42b9d989)

**Comment by daniel1noble** [comment]
Should all be sorted now

**Comment by itchyshin** [comment]
Thanks @daniel1noble
