### ISSUE TITLE
An error when running `orchard_plot`

### ISSUE THREAD

**Issue by itchyshin** [daniel1noble/orchaRd#63]
@daniel1noble - have you come across an error like this?

```
> orchard_plot(mod0, mod = "1", xlab = "logit(overlap %)", group = Study_ID)
Error in .subset2(x, i, exact = exact) : 
  recursive indexing failed at level 2
```

maybe this link is useful

https://stackoverflow.com/questions/52198029/error-in-xi-recursive-indexing-failed-at-level-2

**Comment by daniel1noble** [comment]
I’ve never seen that, but can you try adding quotation marks for “Study_ID” and seeing if that fixes it?Cheers,DanSent from my iPhoneOn 24 Jun 2024, at 1:49 AM, Shinichi Nakagawa ***@***.***> wrote:﻿
@daniel1noble - have you come across an error like this?
> orchard_plot(mod0, mod = "1", xlab = "logit(overlap %)", group = Study_ID)
Error in .subset2(x, i, exact = exact) : 
  recursive indexing failed at level 2

maybe this link is useful
https://stackoverflow.com/questions/52198029/error-in-xi-recursive-indexing-failed-at-level-2

**Comment by itchyshin** [comment]
@daniel1noble 

Sorry - I should not be making that kind of mistake, but even with "Study_ID" - I get this - this seems like a familiar error?

```
> orchard_plot(mod1, mod = "treatment", xlab = "logit(overlap %)", group = "Study_ID")
Error in data.frame(yi, vi, moderator, stdy, type) : 
  arguments imply differing number of rows: 932, 0, 1
```

**Comment by daniel1noble** [comment]
Ha, all good @itchyshin! If it make you feel better, I still forget to add quotes sometimes ;) 

This seems like it could be an issue with missing data. Are there any when fitting the model? I haven't seen this error in a long time, but it seems to crop up now and there so I'm not sure where it might still be coming from.

**Comment by itchyshin** [comment]
@daniel1noble - found out - that I created `StudyID` and did not make it a part of `dat`.
