### ISSUE TITLE
i2_ml()

### ISSUE THREAD

**Issue by daniel1noble** [daniel1noble/orchaRd#9]
Yefeng: "using i2_ml() to calculate confidence intervals for an intercept-only model (rma object), we need to fit intercept-only model with argument “mods = ~ 1”. Otherwise, CIs can not be returned by i2_ml"

**Comment by daniel1noble** [comment]
Need to fix this or make it more clear.

**Comment by itchyshin** [comment]
Probably we want to take bout `data` argument like anybody else. 

I also got this error - 

```
i2_ml(m4, data =  dat3, boot = 10)
The object/variable ('mods_formula') specified for the 'mods' argument is NULL.
```

I think we should probably someone automatically do this - as many people would use `i2_ml` without fitting the intercept as `mod`

**Comment by itchyshin** [comment]
Probably we need to incorporate `tryCatch` or something like that

```
"Bootstrapping [>----------------------------------------------------]   1% ETA:  1mError: Optimizer (nlminb) did not achieve convergence (convergence = 1)"
```
Remember to look at `r2_ml` as well

**Comment by daniel1noble** [comment]
Thanks @itchyshin. TryCatch should already be implemented, but clearly it's still missing something. I'll see if I can figure out where and fix that

**Comment by daniel1noble** [comment]
We have tried this again and cannot track the issues. It seems to be working with this case and many others so closing this issue
